### ISSUE TITLE
Entità "unknown"

### ISSUE THREAD

**Issue by ancientm74** [Bobsilvio/calcio-live#2]
Ciao, intanto complimenti bellissimo lavoro, soltando che da ieri mi da tutte le entità sconosciute, ho anche provato ad eliminare l'integrazione e a rimetterla, ma il problema persiste.
![2024-09-28_150057](https://github.com/user-attachments/assets/746af465-8e93-423d-b35a-54d1a80f989c)

**Comment by Bobsilvio** [comment]
Ciao, mi sembra di vedere che hai creato i sensori con lo spazio nel nome. “Serie a”  può essere “seriea” o “serie_a”

**Comment by ancientm74** [comment]
Si ma automaticamente i sensori vengono creati senza spazio ovvero serie_a.. juventus_fc.... comunque ho provato per scrupolo a mettere seriea nel nome ma non ho risolto. Strano perchè fino a ieri funzionava.
![2024-09-28_164105](https://github.com/user-attachments/assets/caef61f4-68be-46d7-8eff-eb178aa9a09c)

**Comment by Bobsilvio** [comment]
ripartiamo, togli l'integrazione (solo l'integrazione, lascia le card), 
1) scarica la v018 
2) poi riavvia
3) fai la configurazione con api key e nome+campionato
4) se non vedi popolare i sensori dopo 10 minuti, riavvia..
fammi sapere.

**Comment by ancientm74** [comment]
Fatto come hai scritto ma niente tutte le entità sempre "unknown". 
![2024-09-28_175331](https://github.com/user-attachments/assets/1a504574-b2f4-40ea-92b1-639893ff4cb7)


Ho controllato anche sul sito è l'account e ok, l'unica cosa forse strana è questa:
[
![2024-09-28_175031](https://github.com/user-attachments/assets/be9df4b7-eb2e-4800-828c-1401c8e05690)
](url)

**Comment by Bobsilvio** [comment]
il tuo sensore non fa richieste.. aspetta tutta la notte vedi se parte.

**Comment by ancientm74** [comment]
Stamattina ancora non andava, ho risolto utilizzando una nuova chiave API

**Comment by Bobsilvio** [comment]
ottimo
