### ISSUE TITLE
Orario Partite

### ISSUE THREAD

**Issue by marcellomariano** [Bobsilvio/calcio-live#3]
Ciao, innanzitutto complimenti per l'integrazione e per le card. Trovo veramente il tutto molto ben fatto.
Ho riscontrato solo un piccolo problema sull'orario dei match. Come vedi dall'immagine allegata sembra che il sensore del time sia arretrato di un paio d'ore rispetto all'effettivo orario di gioco.

![Screen home ass](https://github.com/user-attachments/assets/bc48a678-85b7-4c6c-9c47-b8d68eb2fcde)

Altro suggerimento: quando si clicca su info escono delle interessanti statistiche sui match, ma lo sfondo è nero, quindi poco leggibile. Suggerirei di lasciarlo bianco o in linea con le impostazioni di illuminazione.

Per il resto, tutto fantastico!

**Comment by Bobsilvio** [comment]
Fixati entrambi i problemi nell 2.1.0

**Comment by Bobsilvio** [comment]
closed
