### ISSUE TITLE
Capire quando la squadra che segui, fa goal

### ISSUE THREAD

**Issue by labactani** [Bobsilvio/calcio-live#4]
Ottima integrazione, a mio avviso piu' elegante di Teamtracker.
Ho solamente un suggerimento (o magari sono le mie capacita' limitate :-)). Per come e' strutturato il sensore, non e' semplice creare un'automazione che ti avvisi quando la squadra che segui, fa goal. Ripeto, forse sono le mie capacita' limitate...

**Comment by Bobsilvio** [comment]
Il sensore è strutturato come deve essere, prova a guardare un sensore del meteo per esempio, i dati vanno negli attributi.

Prova questa automazione, devi cambiare il notify.... con il tuo telefono, il sensore deve essere quello della singola partita(ma funziona anche sulla lista di partite).
Ricordati di cambiare anche il nome della squadra 'Internazionale)

```
alias: Notifica Goal Inter
description: >-
  Invia una notifica quando Inter segna un gol
trigger:
  - platform: template
    value_template: >
      {% for match in state_attr('sensor.calciolive_all_ita_1_internazionale',
      'matches') %}
        {% if match.away_team == 'Internazionale' %}
          {% for event in match.match_details %}
            {% if 'Goal' in event %}
              {% set minuto = event.split("'")[0].split("-")[-1].strip() %}
              {% if minuto | int < 90 %}
                true
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endif %}
      {% endfor %}
condition: []
action:
  - data_template:
      message: >
        {% for match in state_attr('sensor.calciolive_all_ita_1_internazionale',
        'matches') %}
          {% if match.away_team == 'Internazionale' %}
            {% for event in match.match_details %}
              {% if 'Goal' in event %}
                {% set minuto = event.split("'")[0].split("-")[-1].strip() %}
                {% set giocatore = event.split("': ")[1].strip() %}
                {% if minuto | int < 90 %}
                  ⚽ Gol segnato da {{ giocatore }} al {{ minuto }}!
                {% endif %}
              {% endif %}
            {% endfor %}
          {% endif %}
        {% endfor %}
      title: >
        {% for match in state_attr('sensor.calciolive_all_ita_1_internazionale',
        'matches') %}
          {% if match.away_team == 'Internazionale' %}
           {{ match.away_team }} vs {{ match.home_team }}
          {% endif %}
        {% endfor %}
    action: notify.mobile_app_XXXXXX
mode: single
```

**Comment by labactani** [comment]
Grazi mille, sei stato super gentile...non dovevi.
E giusto per chiarire, non intendevo che fosse strutturato male, ci mancherebbe! E' spettacolare.
Il mio commento era piu' dettato dal fatto che, ad esempio in teamtracker, c'e' un attributo chiamato team_score che indica il goal della squadra che si vuole seguire indipendentemente se giochi in casa o fuori. In piu' e' un attributo selezionabile dalla GUI quando si creano automazioni...di nuovo, mio commento precedente dettato dalle mie capacita' limitate ;-) 

Grazie ancora

**Comment by Bobsilvio** [comment]
Devi capire che teamtracker sono anni che affina il codice, io ho fatto tutto in qualche giorno. Conta poi che dopo duro lavoro il vecchio sito funzionava a tratti e ho dovuto rifare da capo in un solo giorno.
Piano piano ascolterò le esigenze di tutti.
