### ISSUE TITLE
Nessujn nome squadra

### ISSUE THREAD

**Issue by radeon79** [Bobsilvio/calcio-live#5]
Innanzitutto complimenti, ti chiedevo il motivo di questo warning: 
Registratore: custom_components.calcio_live.sensori.const
Fonte: custom_components/calcio_live/sensori/scoreboard.py:51
Integrazione: Calcio Live ([documentazione](https://github.com/Bobsilvio/calcio_live), [problemi](https://github.com/Bobsilvio/calcio_live/issues))
Prima occorrenza: 12:33:35 (637 occorrenze)
Ultima registrazione: 17:51:08

Nessun nome squadra fornito, elaborazione di tutte le partite.
Ho configurato come sensori  team napoli, classifica serie a e tutta la serie a.
chiaro che per avere tutta la serie a non ci sta scelta del team però non capisco il warning ripetuto 637 volte.

Inoltre ti volevo chiedere come avere lista cannonieri non la vedo come card.
Complimenti ancora.

**Comment by Bobsilvio** [comment]
ciao é solo un info messa da me quando ho sviluppato il sensore. Che rimuoverò.
La card capocannonieri non esiste piu.. per ora.
Saluti
